const airports = [{
    "code": "AAA",
    "lat": "-17.3595",
    "lon": "-145.494",
    "name": "Anaa Airport",
    "city": "Anaa",
    "state": "Tuamotu-Gambier",
    "country": "French Polynesia",
    "woeid": "12512819",
    "tz": "Pacific\/Midway",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "4921",
    "elev": "7",
    "icao": "NTGA",
    "direct_flights": "2",
    "carriers": "1"
},
{
    "code": "AAE",
    "lat": "36.8236",
    "lon": "7.8103",
    "name": "El Mellah Airport",
    "city": "El Tarf",
    "state": "Annaba",
    "country": "Algeria",
    "woeid": "12510325",
    "tz": "Africa\/Algiers",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "9843",
    "elev": "16",
    "icao": "DABB",
    "direct_flights": "6",
    "carriers": "2"
},
{
    "code": "AAL",
    "lat": "57.0952",
    "lon": "9.85606",
    "name": "Aalborg Airport",
    "city": "Norresundby",
    "state": "Nordjylland",
    "country": "Denmark",
    "woeid": "12512587",
    "tz": "Europe\/Copenhagen",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "http:\/\/www.aal.dk\/",
    "runway_length": "8700",
    "elev": "10",
    "icao": "EKYT",
    "direct_flights": "7",
    "carriers": "10"
},
{
    "code": "AAM",
    "lat": "-24.8",
    "lon": "31.5333",
    "name": "Mala Mala",
    "city": "Mala Mala",
    "state": "",
    "country": "South Africa",
    "woeid": "55921381",
    "tz": "Africa\/Johannesburg",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "4420",
    "elev": "1200",
    "icao": "FAMD",
    "direct_flights": "1",
    "carriers": "1"
},
{
    "code": "ABE",
    "lat": "40.6514",
    "lon": "-75.4342",
    "name": "Lehigh Valley International Airport",
    "city": "Allentown",
    "state": "Pennsylvania",
    "country": "United States",
    "woeid": "12518581",
    "tz": "America\/New_York",
    "phone": "610-266-6000",
    "type": "Airports",
    "email": "",
    "url": "http:\/\/www.lvia.org\/",
    "runway_length": null,
    "elev": null,
    "icao": "KABE",
    "direct_flights": "14",
    "carriers": "11"
},
{
    "code": "ABI",
    "lat": "32.4164",
    "lon": "-99.6803",
    "name": "Abilene Regional Airport",
    "city": "Abilene",
    "state": "Texas",
    "country": "United States",
    "woeid": "12518518",
    "tz": "America\/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "7199",
    "elev": "1790",
    "icao": "KABI",
    "direct_flights": "2",
    "carriers": "4"
},
{
    "code": "ABJ",
    "lat": "5.2556",
    "lon": "-3.9292",
    "name": "Abidjan Port Bouet Airport",
    "city": "Abidjan",
    "state": "Abidjan",
    "country": "Ivory Coast",
    "woeid": "12513870",
    "tz": "Africa\/Abidjan",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "8858",
    "elev": "20",
    "icao": "DIAP",
    "direct_flights": "22",
    "carriers": "29"
},
{
    "code": "ABK",
    "lat": "6.73719",
    "lon": "44.2797",
    "name": "Kabri Dar",
    "city": "Kabri Dar",
    "state": "Ogaden",
    "country": "Ethiopia",
    "woeid": "1317686",
    "tz": "Africa\/Addis_Ababa",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "10935",
    "elev": "1800",
    "icao": "HAKD",
    "direct_flights": "1",
    "carriers": "1"
},
{
    "code": "ABL",
    "lat": "67.1058",
    "lon": "-157.854",
    "name": "Ambler Airport",
    "city": "Kiana",
    "state": "Alaska",
    "country": "United States",
    "woeid": "12518600",
    "tz": "America\/Anchorage",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "2600",
    "elev": "289",
    "icao": "",
    "direct_flights": "2",
    "carriers": "3"
},
{
    "code": "ABM",
    "lat": "-10.9438",
    "lon": "142.453",
    "name": "Bamaga Airport",
    "city": "Seisia",
    "state": "Queensland",
    "country": "Australia",
    "woeid": "12510598",
    "tz": "Australia\/Brisbane",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "6700",
    "elev": "49",
    "icao": "YBAM",
    "direct_flights": "1",
    "carriers": "1"
},
{
    "code": "ABQ",
    "lat": "35.0494",
    "lon": "-106.625",
    "name": "Albuquerque International Airport",
    "city": "Albuquerque",
    "state": "New Mexico",
    "country": "United States",
    "woeid": "12518564",
    "tz": "America\/Denver",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "13375",
    "elev": "5352",
    "icao": "KABQ",
    "direct_flights": "41",
    "carriers": "25"
},
{
    "code": "ABR",
    "lat": "45.4536",
    "lon": "-98.4189",
    "name": "Aberdeen Regional Airport",
    "city": "Aberdeen",
    "state": "South Dakota",
    "country": "United States",
    "woeid": "12518514",
    "tz": "America\/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "6904",
    "elev": "1301",
    "icao": "KABR",
    "direct_flights": "3",
    "carriers": "5"
},
{
    "code": "ABS",
    "lat": "22.3722",
    "lon": "31.6125",
    "name": "Abu Simbel Airport",
    "city": "Abu Simbel",
    "state": "Aswan",
    "country": "Egypt",
    "woeid": "12512656",
    "tz": "Africa\/Cairo",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "8202",
    "elev": "615",
    "icao": "HEBL",
    "direct_flights": "1",
    "carriers": "1"
},
{
    "code": "PWK",
    "lat": "42.1162",
    "lon": "-87.8987",
    "name": "Pal Waukee Airport",
    "city": "Wheeling",
    "state": "Illinois",
    "country": "United States",
    "woeid": "12521282",
    "tz": "America\/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "5000",
    "elev": "647",
    "icao": "KPWK",
    "direct_flights": "2",
    "carriers": "1"
},
{
    "code": "PWM",
    "lat": "43.6475",
    "lon": "-70.3103",
    "name": "Jetport International Airport",
    "city": "Portland",
    "state": "Maine",
    "country": "United States",
    "woeid": "12520368",
    "tz": "America\/New_York",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "6800",
    "elev": "74",
    "icao": "KPWM",
    "direct_flights": "17",
    "carriers": "18"
}
];

function findAirport() {
    let searchData = document.getElementById('searchData');
    let findText = document.getElementById("findText").value;
    const lowerFindtext = findText.toLowerCase();
    searchData.innerHTML = "";
    const result = airports.find((element) => {
        if (element.country.toLocaleLowerCase() == lowerFindtext) {
            let tr = document.createElement('tr');
            let td = document.createElement('td');
            let td2 = document.createElement('td');
            let tdData = document.createTextNode(element.name);
            let tdData2 = document.createTextNode(element.country);
            td.appendChild(tdData);
            td2.appendChild(tdData2);
            tr.appendChild(td);
            tr.appendChild(td2);
            searchData.appendChild(tr);
        }
    });
}